---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
SSViewer:
  theme: 'acs'

SiteConfig:
  extensions:
    - SiteConfig_Extension

SiteTree:
  extensions:
    - SiteTreeSetting

BlockWidget:
  extensions:
    - ResourceBlockWidget_Extension