---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
SSViewer:
  theme: 'acs'

SiteConfig:
  extensions:
    - SiteConfig_Extension
    - JobSetting

SiteTree:
  extensions:
    - SiteTreeSetting

Member:
  extensions:
    - Member_Extension

BlockWidget:
  extensions:
    - ResourceBlockWidget_Extension

Blog:
  extensions:
    - Blog_Extension
Blog_Controller:
  extensions:
    - Blog_Controller_Extension
BlogPost:
  extensions:
    - BlogPost_Extension
BlogPost_Controller:
  extensions:
    - BlogPost_Controller_Extension
BlogCategory:
  extensions:
    - BlogCategory_Extension

Image:
  extensions:
    - CaseStudyFeaturedImage_DataExtension
    - CaseStudyGalleryImages_DataExtension

BlockWidget:
  extensions:
    - BlockWidget_Extension

UserDefinedForm:
  email_template_directory: themes/acs/templates/email